### PR TITLE
Add a function to pass the filter parameters from the grid field to t…

### PR DESCRIPTION
**Pull request by lucasfrey**
…he prev / next button. So it go prev / next into the filtered grid field and not only by ID
Happy to discuss the way of implementing it. But I've found the function useful

### CODE REVIEW

**Comment by charles-ritchie** [comment]
Came across the same issue. I think your fix is overly complex. Whey not the following?

Get search request var like so:
```php 
$params = array(
     'q' => (array)$this->gridFieldRequest->gerRequest()->getVar('q')
);  

$searchVars = (bool)$params ? '?' . http_build_query($params) : null;
```
Update links like this:
```php
$prevLink = $previousRecordID ? Controller::join_links($this->gridFieldRequest->gridField->Link(),"item", $previousRecordID . $searchVars) : "javascript:void(0);";
```
and
```php
$prevLink = $nextRecordID ? Controller::join_links($this->gridFieldRequest->gridField->Link(),"item", $nextRecordID . $searchVars) : "javascript:void(0);";
```

**Comment by unclecheese** [comment]
Have you confirmed that this patch works?

**Comment by lucasfrey** [comment]
I updated the pull request with charles-ritchie amends, it looks better now. 
I confirm that this patch works.

**Comment by unclecheese** [comment]
So this doesn't persist the sort of the grid, just the filter?

**Comment by 3Dgoo** [comment]
I have just tested this out on SilverStripe 3.1 and can confirm this patch works to fix the filter issue. It does not fix the GridField sort issue, but hopefully that can be worked out in a future pull request.

**Pull request merged**
